# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

resources:
- repo: self

stages:
- stage: BuildAndTest
  displayName: "Build And Test Stage "
  jobs:
  - job: BuildAndTestJob
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - task: Gradle@2
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        gradleWrapperFile: '$(System.DefaultWorkingDirectory)/gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: 1.17
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'clean build -x test'
      displayName: "Build And Test Backend"

    - script: |
        echo "Changing file permissions..."
        chmod +x $(System.DefaultWorkingDirectory)/gradlew
      displayName: 'Set execute permission for gradlew'
    
- stage: DeployDockerImage
  jobs:
  - job: DeployDockerImageJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: Docker@2
      inputs:
        containerRegistry: 'bootcampquizapi'
        command: login
        arguments: '-u $(DOCKER_USER) -p $(DOCKER_PASS) bootcampquizapi.azurecr.io'
    - script: |
        docker build -t bootcampquizapi.azurecr.io/bootcampquiz:latest .
        docker push bootcampquizapi.azurecr.io/bootcampquizapi:latest
      displayName: "Build And Push Docker Image"

- stage: TestAndDeploy
  dependsOn:
  - BuildAndTest
  - DeployDockerImage
