# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  displayName: 'Build backend'
  steps:
#  - task: JavaToolInstaller@0
#    inputs:
#      versionSpec: '1.17'
#      jdkArchitectureOption: 'x64'
#      jdkSourceOption: 'PreInstalled'

  - task: Gradle@2
    inputs:
      workingDirectory: '$(system.defaultWorkingDirectory)'
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'

 # - task: PublishBuildArtifacts@1