version: '3'
services:
  postgres:
    image: postgres:11
    container_name: quizDB
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  demo:
    image: 'demo:latest'
    build:
      context: .
    container_name: quizApp
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"
    depends_on:
      - postgres
